export const ENDPOINT = {
  LOGIN: "auth/login",
  GOOGLE_LOGIN: "auth/google/login",
  GOOGLE_LOGIN_GET_TOKEN: "auth/google/getToken",
  USERS: "users/current-user",
  SIGN_UP: "auth/register",
  SIGN_OUT: "auth/logout",
  REFRESH_TOKEN: "auth/refresh",
  WORDS: "words",
  WORDS_DASHBOARD: "words/dashboard",
  PRACTICES: "practices",
  WRITING: "writing",
  TRANSLATION: "translation",
  LISTENING: "listening",
} as const;
