-- Listening challenges are a shared pool generated by a background job (not per-user), since each
-- one requires an AI voice-generation call that is limited (see listening_voice_generation_stats).
CREATE TABLE listening_challenges
(
    id         BIGSERIAL PRIMARY KEY,
    level      VARCHAR(20) NOT NULL,
    sentence   TEXT        NOT NULL,
    voice_data BYTEA       NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);

CREATE INDEX idx_listening_challenges_level ON listening_challenges (level);

CREATE TABLE listening_submissions
(
    id           BIGSERIAL PRIMARY KEY,
    challenge_id BIGINT    NOT NULL REFERENCES listening_challenges (id) ON DELETE CASCADE,
    user_id      BIGINT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    transcript   TEXT      NOT NULL,
    correct      BOOLEAN   NOT NULL,
    feedback     TEXT,
    created_at   TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP NOT NULL DEFAULT NOW(),
    created_by   VARCHAR(100),
    updated_by   VARCHAR(100)
);

CREATE INDEX idx_listening_submissions_user_id ON listening_submissions (user_id);
CREATE INDEX idx_listening_submissions_challenge_id ON listening_submissions (challenge_id);

-- Single-row global counter of AI voice-generation calls made so far, so the generation job can stop
-- once the free-tier budget (10 requests) is used up.
CREATE TABLE listening_voice_generation_stats
(
    id            BIGSERIAL PRIMARY KEY,
    request_count INT NOT NULL DEFAULT 0
);

INSERT INTO listening_voice_generation_stats (request_count) VALUES (0);
